import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
	return (
<div>
			<head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<div class="flex flex-col h-screen justify-between">
				<main className="pb-20">
					<div className="h-64 bg-yellow-50"></div>
					<div className="bg-white px-5 py-7">
						<h1 className="text-2xl font-normal text-gray-500"><span className="font-bold">Hooked :</span> How to Build Habid-Forming Products</h1>
						<h3 className="text-red-400 mt-3">Nir Eyal</h3>
						<p className="text-gray-500 mt-3">How do successful companies create products people can’t put down? Why do some products capture widespread attention while others flop? Why do some products capture widespread attention while others flop? Why do some products capture widespread attention while others flop?</p>
						<p className="text-gray-500 mt-3">How do successful companies create products people can’t put down? Why do some products capture widespread attention while others flop? Why do some products capture widespread attention while others flop? Why do some products capture widespread attention while others flop?</p>
						<p className="text-gray-500 mt-3">How do successful companies create products people can’t put down? Why do some products capture widespread attention while others flop? Why do some products capture widespread attention while others flop? Why do some products capture widespread attention while others flop?</p>
						<p className="text-gray-500 mt-3">How do successful companies create products people can’t put down? Why do some products capture widespread attention while others flop? Why do some products capture widespread attention while others flop? Why do some products capture widespread attention while others flop?</p>
					</div>

				</main>

				<footer class="w-80 fixed bottom-5 px-8 py-5 grid grid-cols-3 gap-4 bg-white shadow-lg rounded-md">
					<div className="text-gray-600">
						<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
						</svg>
						<p className="text-xs">Home</p>
					</div>
					<div className="text-gray-600">
						<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 4v12l-4-2-4 2V4M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
						</svg>
						<p className="text-xs">Libraries</p>
					</div>
					<div className="text-gray-600">
						<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
						</svg>
						<p className="text-xs">Profile</p>
					</div>
				</footer>
				</div>
		</div>
	)
}
