import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
	return (
		<div>
			<head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<div class="flex flex-col h-screen justify-between">
				<main className="px-5 pb-20">
				{/*search*/}
					<div className="mt-14 pt-2 relative mx-auto text-gray-300 p-3 rounded-lg flex bg-white mb-8">
						<button type="submit">
							<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
								<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
							</svg>
						</button>
						<input className="px-5 pr-16 focus:outline-none" type="search" name="search" placeholder="Search"/>
					</div>
				{/*fim search*/}
					<h1 className="text-2xl font-normal">Hi, <span className="font-semibold text-red-400">Mehmed Al Fatih</span> 👋</h1>
				
				{/*slide 01*/}
				<div className="mt-7">
					<div className="flex relative">
						<h3 className="text-gray-600 text-lg">Discover new book</h3>
						<h3 className="text-blue-400 text-lg absolute right-0">More</h3>
					</div>
					<div className="h-32 relative">
						<Image src="/images/banner.png" layout='fill' />
					</div>
				</div>
				{/*fim slide*/}

				{/*slide 02*/}
				<div className="mt-7">
					<div className="flex relative">
						<h3 className="text-gray-600 text-lg">Currently Reading</h3>
						<h3 className="text-blue-400 text-lg absolute right-0">All</h3>
					</div>
					<div className="h-32 relative">
						<Image src="/images/banner02.png" layout='fill' />
					</div>
				</div>
				{/*fim slide*/}

			{/*slide 03*/}
				<div className="mt-7">
					<div className="flex relative">
						<h3 className="text-gray-600 text-lg">Reviews of The Days</h3>
						<h3 className="text-blue-400 text-lg absolute right-0">All Video</h3>
					</div>
					<div className="h-32 relative">
						<Image src="/images/banner02.png" layout='fill' />
					</div>
				</div>
				{/*fim slide*/}

				</main>

				<footer class="w-screen fixed bottom-0 px-8 py-5 grid grid-cols-3 gap-4 bg-white">
					<div className="text-gray-600">
						<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
						</svg>
						<p className="text-xs">Home</p>
					</div>
					<div className="text-gray-600">
						<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 4v12l-4-2-4 2V4M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
						</svg>
						<p className="text-xs">Libraries</p>
					</div>
					<div className="text-gray-600">
						<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
						</svg>
						<p className="text-xs">Profile</p>
					</div>
				</footer>
				</div>
		</div>
	)
}
